using System;
using Newtonsoft.Json;

namespace TicTacToeMultiplayer
{
    /// <summary>
    /// Socket.IO event names emitted and consumed by the current backend.
    /// </summary>
    public static class SocketEvents
    {
        // Client -> server
        public const string CreateRoom = "create-room";
        public const string JoinRoom = "join-room";
        public const string MakeMove = "make-move";
        public const string Reconnect = "reconnect";

        // Server -> client
        public const string RoomCreated = "room-created";
        public const string RoomJoined = "room-joined";
        public const string PlayerJoined = "player-joined";
        public const string GameStarted = "game-started";
        public const string MoveResult = "move-result";
        public const string PlayerDisconnected = "player-disconnected";
        public const string PlayerReconnected = "player-reconnected";
        public const string RoomState = "room-state";
        public const string Error = "error";
    }

    #region Client-to-server socket payloads

    [Serializable]
    public sealed class CreateRoomRequest
    {
        [JsonProperty("playerId")]
        public string PlayerId;
    }

    [Serializable]
    public sealed class JoinRoomRequest
    {
        [JsonProperty("roomId")]
        public string RoomId;

        [JsonProperty("playerId")]
        public string PlayerId;
    }

    [Serializable]
    public sealed class MakeMoveRequest
    {
        [JsonProperty("roomId")]
        public string RoomId;

        [JsonProperty("playerId")]
        public string PlayerId;

        [JsonProperty("row")]
        public int Row;

        [JsonProperty("col")]
        public int Col;
    }

    [Serializable]
    public sealed class ReconnectRequest
    {
        [JsonProperty("playerId")]
        public string PlayerId;
    }

    #endregion

    #region Shared server payload objects

    [Serializable]
    public sealed class PlayerSummary
    {
        [JsonProperty("playerId")]
        public string PlayerId;

        [JsonProperty("symbol")]
        public string Symbol;

        [JsonProperty("connected")]
        public bool Connected;
    }

    [Serializable]
    public sealed class MoveSummary
    {
        [JsonProperty("playerId")]
        public string PlayerId;

        [JsonProperty("row")]
        public int Row;

        [JsonProperty("col")]
        public int Col;

        // ISO-8601 timestamp generated by the backend.
        [JsonProperty("timestamp")]
        public string Timestamp;
    }

    [Serializable]
    public sealed class ErrorPayload
    {
        [JsonProperty("message")]
        public string Message;
    }

    #endregion

    #region Server-to-client socket payloads

    [Serializable]
    public sealed class RoomCreatedPayload
    {
        [JsonProperty("roomId")]
        public string RoomId;

        [JsonProperty("player")]
        public PlayerSummary Player;
    }

    // Runtime payload is identical to room-created, but it is a separate event.
    [Serializable]
    public sealed class RoomJoinedPayload
    {
        [JsonProperty("roomId")]
        public string RoomId;

        [JsonProperty("player")]
        public PlayerSummary Player;
    }

    [Serializable]
    public sealed class PlayerJoinedPayload
    {
        [JsonProperty("playerId")]
        public string PlayerId;

        [JsonProperty("symbol")]
        public string Symbol;

        [JsonProperty("players")]
        public PlayerSummary[] Players;
    }

    [Serializable]
    public sealed class GameStartedPayload
    {
        // A cell is "X", "O", or null. The array is always 3 x 3.
        [JsonProperty("board")]
        public string[][] Board;

        [JsonProperty("currentPlayer")]
        public PlayerSummary CurrentPlayer;

        // Unix epoch milliseconds, not a duration.
        [JsonProperty("turnDeadline")]
        public long TurnDeadline;

        [JsonProperty("playerX")]
        public PlayerSummary PlayerX;

        [JsonProperty("playerO")]
        public PlayerSummary PlayerO;
    }

    [Serializable]
    public sealed class MoveResultPayload
    {
        [JsonProperty("success")]
        public bool Success;

        // Present when Success is false.
        [JsonProperty("error")]
        public string Error;

        // Absent for a scheduled timeout and failed move.
        [JsonProperty("move")]
        public MoveSummary Move;

        [JsonProperty("board")]
        public string[][] Board;

        // Null once the game has finished.
        [JsonProperty("currentPlayer")]
        public PlayerSummary CurrentPlayer;

        // Null once the game has finished.
        [JsonProperty("turnDeadline")]
        public long? TurnDeadline;

        [JsonProperty("winner")]
        public PlayerSummary Winner;

        // Three [row, col] pairs on a normal win, otherwise null or absent.
        [JsonProperty("winningCells")]
        public int[][] WinningCells;

        [JsonProperty("isDraw")]
        public bool IsDraw;

        // Current implementation sends this only from the scheduled timeout path.
        [JsonProperty("timeoutWin")]
        public bool TimeoutWin;
    }

    [Serializable]
    public sealed class PlayerConnectionPayload
    {
        [JsonProperty("playerId")]
        public string PlayerId;
    }

    [Serializable]
    public sealed class RoomStatePayload
    {
        [JsonProperty("roomId")]
        public string RoomId;

        // OPEN, ACTIVE, or FINISHED.
        [JsonProperty("status")]
        public string Status;

        [JsonProperty("players")]
        public PlayerSummary[] Players;

        [JsonProperty("board")]
        public string[][] Board;

        [JsonProperty("currentPlayer")]
        public PlayerSummary CurrentPlayer;

        [JsonProperty("turnDeadline")]
        public long? TurnDeadline;

        [JsonProperty("winner")]
        public PlayerSummary Winner;

        [JsonProperty("winningCells")]
        public int[][] WinningCells;

        [JsonProperty("isDraw")]
        public bool IsDraw;

        [JsonProperty("moves")]
        public MoveSummary[] Moves;
    }

    #endregion

    #region REST API payloads

    [Serializable]
    public sealed class HealthResponse
    {
        [JsonProperty("status")]
        public string Status;

        [JsonProperty("server")]
        public string Server;
    }

    [Serializable]
    public sealed class RoomSummaryResponse
    {
        [JsonProperty("roomId")]
        public string RoomId;

        [JsonProperty("status")]
        public string Status;

        [JsonProperty("playerCount")]
        public int PlayerCount;

        [JsonProperty("players")]
        public PlayerSummary[] Players;

        [JsonProperty("createdAt")]
        public string CreatedAt;

        [JsonProperty("updatedAt")]
        public string UpdatedAt;
    }

    [Serializable]
    public sealed class RoomDetailsResponse
    {
        [JsonProperty("roomId")]
        public string RoomId;

        [JsonProperty("status")]
        public string Status;

        [JsonProperty("players")]
        public PlayerSummary[] Players;

        [JsonProperty("game")]
        public RestGameState Game;

        [JsonProperty("createdAt")]
        public string CreatedAt;

        [JsonProperty("updatedAt")]
        public string UpdatedAt;
    }

    [Serializable]
    public sealed class RestGameState
    {
        [JsonProperty("board")]
        public string[][] Board;

        [JsonProperty("currentPlayer")]
        public PlayerSummary CurrentPlayer;

        [JsonProperty("turnDeadline")]
        public long? TurnDeadline;

        [JsonProperty("winner")]
        public PlayerSummary Winner;

        [JsonProperty("winningCells")]
        public int[][] WinningCells;

        [JsonProperty("isDraw")]
        public bool IsDraw;

        [JsonProperty("moves")]
        public MoveSummary[] Moves;

        [JsonProperty("startedAt")]
        public string StartedAt;

        [JsonProperty("completedAt")]
        public string CompletedAt;
    }

    [Serializable]
    public sealed class RestErrorResponse
    {
        [JsonProperty("error")]
        public string Error;
    }

    #endregion
}
